#!/bin/sh

# Variables
line="----------------------------------------------"


echo "[+] Welcome to fedora dotfiles install script!"

echo $line

# Configure DNF Package Manager
configure_dnf(){
  echo "[+] Configuring DNF..."
  sudo echo "fastestmirror=True" > /etc/dnf/dnf.conf
  sudo echo "max_parallel_downloads=10" > /etc/dnf/dnf.conf
  sudo echo "defaultyes=True" > /etc/dnf/dnf.conf

  sudo dnf update

  # Enable the RPM fusion repos
  sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpmfusion # Free
  sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm # Not Free
}

configure_dnf
test ${?} -eq 0 || {}
echo "[+] DNF Successfully configured!"


# Things to do 
sudo dnf remove powerline  # Neovim error regarding powerline

# Insatlling Packages
echo "[+] Installing Packages..."

